.TH "EJSON-KMS" "1"
.nh
.ad l


.SH NAME
.PP
ejson\-kms\-add \- add a secret


.SH SYNOPSIS
.PP
\fBejson\-kms add NAME\fP


.SH DESCRIPTION
.PP
add: Add a secret to a secrets file.

.PP
The name of the secret must be in lowercase and can only contain letters,
digits and underscores. It cannot start with a digit. This is to ensure
compatibility with the shell when using the export command.

.PP
An optional, freeform, description can be provided. Use it to describe what the
item is for, how to rotate it, who is responsible and when...

.PP
It will ask you to type the secret at runtime, to avoid saving it to your
shell history. If you need to pass in the contents of a file (such as TLS keys),
you can pipe it's contents to stdin.
Please be mindful of your bash history when piping in strings.


.SH OPTIONS
.PP
\fB\-\-description\fP=""
    freeform description of the secret

.PP
\fB\-\-path\fP=".secrets.json"
    path of the secrets file


.SH EXAMPLE
.PP
.RS

.nf
ejson\-kms add password
ejson\-kms add password \-\-path="secrets.json"
ejson\-kms add password \-\-description="Nuclear launch code"
cat tls\-cert.key | ejson\-kms add tls\_key

.fi
.RE


.SH SEE ALSO
.PP
\fBejson\-kms(1)\fP
