.TH "EJSON-KMS" "1"
.nh
.ad l


.SH NAME
.PP
ejson\-kms\-rotate\-kms\-key \- rotates the KMS key used to encrypt the secrets


.SH SYNOPSIS
.PP
\fBejson\-kms rotate\-kms\-key NEW\_KMS\_KEY\_ID\fP


.SH DESCRIPTION
.PP
rotate\-kms\-key: Rotates the KMS key used to encrypt a secrets file.

.PP
This command will decrypt all your secrets, and re\-encrypt them using the
provided new KMS key.
The original file will be overwritten.


.SH OPTIONS
.PP
\fB\-\-path\fP=".secrets.json"
    path of the secrets file


.SH EXAMPLE
.PP
.RS

.nf
ejson\-kms rotate\-kms\-key arn:aws:kms:us\-east\-1:123456789012:alias/MyAliasName

.fi
.RE


.SH SEE ALSO
.PP
\fBejson\-kms(1)\fP
