.TH "EJSON-KMS" "1"
.nh
.ad l


.SH NAME
.PP
ejson\-kms\-rotate \- rotate a secret


.SH SYNOPSIS
.PP
\fBejson\-kms rotate NAME\fP


.SH DESCRIPTION
.PP
rotate: Rotate a secret from a secrets file.

.PP
This will decrypt the given secret, check that the values are indeed different,
and store the new encrypted value.

.PP
It will ask you to type the secret at runtime, to avoid saving it to your
shell history. If you need to pass in the contents of a file (such as TLS keys),
you can pipe it's contents to stdin.
Please be mindful of your bash history when piping in strings.


.SH OPTIONS
.PP
\fB\-\-path\fP=".secrets.json"
    path of the secrets file


.SH EXAMPLE
.PP
.RS

.nf
ejson\-kms rotate password
cat tls\-cert.key | ejson\-kms rotate tls\_key

.fi
.RE


.SH SEE ALSO
.PP
\fBejson\-kms(1)\fP
